### ISSUE TITLE
akimous command is not path.

### ISSUE THREAD

**Issue by Jaimecclin** [akimous/akimous#5]
I pull the image from docker hub and run it in this docker commnand,

```
docker run -v D:\akimous\:/home/user -p 8787:3179 --net=none --name akimous --rm -it red8012/akimous-dev-environment akimous
```
Note: 
1. red8012/akimous-dev-environment is the image I pull from docker hub.
2. It seems there is network problem so I need to add"--net=none ".
In my opinion, it's the same with your. I can start up the container but no this command in search path.

```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"akimous\": executable file not found in $PATH": unknown.

That means I still cannot run it on Windows system. Any suggestion?

**Comment by red8012** [comment]
Oops. It seems that you pulled the wrong image.
As stated on the [website](https://akimous.com/start) and the README file, the correct command is `docker run --mount type=bind,source=$HOME,target=/home/user -p 127.0.0.1:3179:3179 -it red8012/akimous akimous`.

`akimous-dev-environment` is only meant to be used in my CircleCI pipeline. Actually, it does not contain Akimous program at all. Therefore, please use `red8012/akimous`.

If I missed something, feel free to reopen it.

**Comment by red8012** [comment]
I'll try to make `akimous-dev-environment` have a different README indicating it is not meant for normal use, and it does not contain the actual program.
